config/routes.rb
Rails.application.routes.draw do
  resources :transactionhistories
  devise_for :users , controllers: {
    registrations: 'user/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/transactions' , to: 'transactions#index' , as: 'transaction'
  get '/topups' , to: 'transactionhistories#topup', as: 'topup'
 root to: 'transactionhistories#index'
end

app/models/transactionhistory.rb
class Transactionhistory < ApplicationRecord
    belongs_to :user
end

app/controllers/transactionhistories_controller.rb
class TransactionhistoriesController < ApplicationController
  before_action :set_transactionhistory, only: %i[ show 
   update destroy ]
  before_action :authenticate_user!
  before_action :initialize_client

  def topup
    @userpoints = current_user.current_points
  end

  def index
    
    if Transactionhistory.last.blank?
      Transactionhistory.create(bet:"admin",amountofbet:1000,user_id:current_user.id,result:"admin",
                                ifwin:"admin",currentpoints:0,pointsaftermatch:0)
    end
    @lasttransaction = Transactionhistory.last
    @user = current_user.current_points 
    @pointsaftermatch = @lasttransaction.pointsaftermatch

    if @user <= 0 
      redirect_to edit_user_registration_path
    end


    @transactionhistories = Transactionhistory.all
    @battles = @client.getPlayerByPowerstats
    @battles2 = @client.getPlayerByPowerstats
    @transactionhistory = current_user.transactionhistories.build
   
  end

  # GET /transactionhistories/1 or /transactionhistories/1.json
  def show
  end

  # GET /transactionhistories/new
  def new
    @transactionhistory = current_user.transactionhistories.build
  end

  
  def edit
    
    number = 5
    randomnumber = rand(10)
    @transactionhistory = Transactionhistory.last

        if randomnumber >= number
            @transactionhistory.update(result: "player one")
            @playeronewin = @transactionhistory.result
        elsif randomnumber < number
            @transactionhistory.update(result: "player two")
            @playertwowin = @transactionhistory.result
  
        end

        if @transactionhistory.bet == @transactionhistory.result
            @transactionhistory.update(ifwin: "WIN")

        elsif @transactionhistory.bet != @transactionhistory.result
              @transactionhistory.update(ifwin: "LOSE")
        end

        if @transactionhistory.ifwin == "WIN"
          current_user.update(current_points: current_user.current_points + @transactionhistory.amountofbet)
        @transactionhistory.update(pointsaftermatch:current_user.current_points)
        else
          current_user.update(current_points: current_user.current_points - @transactionhistory.amountofbet)
          @transactionhistory.update(pointsaftermatch:current_user.current_points)
        end
  
  end

  # POST /transactionhistories or /transactionhistories.json
  def create
    
  index
    @transactionhistory = Transactionhistory.new(transactionhistory_params)  
    @bet = @transactionhistory.amountofbet
    @lasttransaction=Transactionhistory.last
    

        if @bet > @user
            respond_to do |format|
              format.js { render :js => "error();" }
            end
        end

      
        if@transactionhistory.save
            @user = @user - @bet
            @transactionhistory.update(pointsaftermatch:@lasttransaction.pointsaftermatch)
        end
  end

  # PATCH/PUT /transactionhistories/1 or /transactionhistories/1.json
  def update
    respond_to do |format|
      if @transactionhistory.update(transactionhistory_params)
        format.html { redirect_to @transactionhistory, notice: "Transactionhistory was successfully updated." }
        format.json { render :show, status: :ok, location: @transactionhistory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transactionhistory.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /transactionhistories/1 or /transactionhistories/1.json
  def destroy
    @transactionhistory.destroy
    respond_to do |format|
      format.html { redirect_to transactionhistories_url, notice: "Transactionhistory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transactionhistory
      @transactionhistory = Transactionhistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transactionhistory_params
      params.require(:transactionhistory).permit(:bet,:amountofbet,:user_id,:currentpoints)
    end

      def initialize_client
          @client = Superhero::Client.new
      end
    
    
  

end

app/helpers/transactionhistories_helper.rb
module TransactionhistoriesHelper
end

app/views/transactionhistories/_form.html.erb
<%= form_with(model: transactionhistory) do |form| %>
  <% if transactionhistory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transactionhistory.errors.count, "error") %> prohibited this transactionhistory from being saved:</h2>

      <ul>
        <% transactionhistory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactionhistories/create.js.erb
document.getElementById('player-one-bet-amount').value ='';
document.getElementById('player-two-bet-amount').value='';
document.getElementById('bet-interface').style.visibility="hidden";
document.getElementById('bet-interface-for-player-two').style.visibility="hidden";
document.getElementById('fight-button').style.visibility="visible"
document.getElementById('e-wallet').innerHTML = "Current points: <%=@user%> "

app/views/transactionhistories/edit.html.erb
<h1>Editing Transactionhistory</h1>

<%= render 'form', transactionhistory: @transactionhistory %>

<%= link_to 'Show', @transactionhistory %> |
<%= link_to 'Back', transactionhistories_path %>

app/views/transactionhistories/edit.js.erb
document.getElementById('player-one-button').disabled = true
document.getElementById('player-two-button').disabled = true
document.getElementById('fight-button').disabled=true
document.getElementById('who-wins').innerHTML = "<%=@transactionhistory.result%> WINS"
document.getElementById('winorlose').innerHTML = " YOU <%=@transactionhistory.ifwin%>"
document.getElementById('amount').innerHTML = "Amount you <%=@transactionhistory.ifwin%> is <%=@transactionhistory.amountofbet%>"
document.getElementById('next-fight').style.visibility="visible";

app/views/transactionhistories/index.html.erb
<body class="bg-white.bg-gradient">
<style>
.container{
  
    width:200px;
    padding:0px;
   
}

.skill {
    background-color: orange;
    color:  white;
    text-align: right;
    font-size: 15px;
    padding: 0px;
}
.intelligence{
  width:  <%= @battles["powerstats"]["intelligence"] %>%
}
.intelligence2{
  width:  <%= @battles2["powerstats"]["intelligence"] %>%
}

.strength{
  width:  <%= @battles["powerstats"]["strength"] %>%
}
.strength2{
  width:  <%= @battles2["powerstats"]["strength"] %>%
}
.speed{
  width:  <%= @battles["powerstats"]["speed"] %>%
}
.speed2{
  width:  <%= @battles2["powerstats"]["speed"] %>%
}
.durability{
  width:  <%= @battles["powerstats"]["durability"] %>%
}
.durability2{
  width:  <%= @battles2["powerstats"]["durability"] %>%
}
.power{
  width:  <%= @battles["powerstats"]["power"] %>%
}
.power2{
  width:  <%= @battles2["powerstats"]["power"] %>%
}
.combat{
  width:  <%= @battles["powerstats"]["combat"] %>%
}
.combat2{
  width:  <%= @battles2["powerstats"]["combat"] %>%
}
</style>

<nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-info">
  <span id="header-title" class="container-fluid"> Battle of Superheroes </span>
  <span id="e-wallet">Current points: <%= @user %></span>

 <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  
      <div  id="signout" class="d-flex">
        <button class="btn btn-info">
        <% if user_signed_in? %>
        <%= link_to "Signout" , destroy_user_session_path, method: :delete %>
        <%end%></button>
      </div>
    </div>
  </div>
</nav>







<div id="index-page">

  <div class="players">
      <div id="player-one-name"><%= @battles["name"] %></div> 
      <img src = <%= @battles["image"]["url"] %>></img>

      <div class="test">
          <div class="stats">Intelligence </div>
            <div class="container">
                  <div class="skill intelligence bg-danger">
                    <%= @battles["powerstats"]["intelligence"] %>
                  </div>
          </div>
      </div>

      <div class="test">
          <div class="stats">Strength </div>
            <div class="container">
                  <div class="skill strength bg-danger">
                    <%= @battles["powerstats"]["strength"] %>
                  </div>
          </div>
      </div>

      <div class="test">
        <div class="stats">Speed </div>
          <div class="container">
                <div class="skill speed bg-danger">
                  <%= @battles["powerstats"]["speed"] %>
                </div>
          </div>
      </div>

      <div class="test">
          <div class="stats">Durability </div>
            <div class="container">
                  <div class="skill durability bg-danger">
                    <%= @battles["powerstats"]["durability"] %>
                  </div>
          </div>
      </div>

      <div class="test">
          <div class="stats">Power </div>
             <div class="container">
                    <div class="skill power bg-danger">
                      <%= @battles["powerstats"]["power"] %>
                    </div>
            </div>
      </div>

      <div class="test">
        <div class="stats">Combat </div>
          <div class="container">
                <div class="skill combat bg-danger">
                  <%= @battles["powerstats"]["combat"] %>
                </div>
           </div>
      </div>

  </div>


<div id="vs" class="players">
  <div id="vs-letter">VS </div>
  <div id="qwerty" class="text-warning bg-dark"></div>
</div>


  <div class="players">
  <div id="player-two-name"><%= @battles2["name"] %></div>
      <div class="image"><img src = <%= @battles2["image"]["url"] %>></img></div>
     
      <div class="test">
         <div class="stats">Intelligence </div>
            <div class="container">
                  <div class="skill intelligence2 bg-primary">
                    <%= @battles2["powerstats"]["intelligence"] %>
                  </div>
             </div>
      </div>

      <div class="test">
         <div class="stats">Strength </div>
            <div class="container">
                  <div class="skill strength2 bg-primary">
                    <%= @battles2["powerstats"]["strength"] %>
                  </div>
             </div>
      </div>

      <div class="test">
      <div class="stats">Speed </div>
         <div class="container">
               <div class="skill speed2 bg-primary">
                 <%= @battles2["powerstats"]["speed"] %>
               </div>
          </div>
   </div>

   <div class="test">
   <div class="stats">Durability </div>
      <div class="container">
            <div class="skill durability2 bg-primary">
              <%= @battles2["powerstats"]["durability"] %>
            </div>
       </div>
    </div>

    <div class="test">
    <div class="stats">Power </div>
      <div class="container">
            <div class="skill power2 bg-primary">
              <%= @battles2["powerstats"]["power"] %>
            </div>
        </div>
    </div>

    <div class="test">
    <div class="stats">Combat </div>
      <div class="container">
            <div class="skill combat2 bg-primary">
              <%= @battles2["powerstats"]["combat"] %>
            </div>
        </div>
    </div>
    
  </div>
  
</div>
<div id="result" class="container">
<div id="who-wins"></div>
<div id="winorlose"></div>
<div id="amount"></div>
<div id="next-fight"> <button class="btn-primary">Click for next fight </button></div>
</div>

<div id="betting-div">
  <div id="player-one-side">
    

    <div id="bet-interface">
      <%= form_for @transactionhistory, remote: true do |form| %>
        <% if @transactionhistory.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(transactionhistory.errors.count, "error") %> prohibited this transactionhistory from being saved:</h2>
            <ul>
              <% @transactionhistory.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
           <% end %>
      
   
        <%= form.hidden_field :bet , value: "player one" %>
        <%= form.hidden_field :currentpoints, value: @user %>
        <%= form.hidden_field :user_id , value: current_user.id%>
        <%= form.label :amount %>
        <%=form.text_field :amountofbet , id: 'player-one-bet-amount' %>
        <%= form.submit "Place bet" , id: 'submit-button-one',class: 'btn btn-danger' %>
        <%end%>
       
  </div>
  
<br>
<button id="player-one-button"class="btn btn-danger ><a  href= "<%= transactionhistories_url %>" data-remote="true"><%= @battles["name"] %></a></button>
</div>


<button id= "fight-button"class="btn btn-success" ><a href= "<%= edit_transactionhistory_path(@lasttransaction) %>" data-remote="true">FIGHT </a></button>

<div id="player-two-side">


<div id="bet-interface-for-player-two">

      <%= form_for @transactionhistory, remote: true do |form| %>
        <% if @transactionhistory.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(transactionhistory.errors.count, "error") %> prohibited this transactionhistory from being saved:</h2>

            <ul>
              <% @transactionhistory.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

            <%= form.hidden_field :bet , value: "player two" %>
            <%= form.hidden_field :currentpoints, value: @user %>
            <%= form.hidden_field :user_id , value: current_user.id%>
            <%= form.label :amount %>
            <%=form.text_field :amountofbet , id: 'player-two-bet-amount' %>
            <%= form.submit "Place bet" , id: 'submit-button-two', class: 'btn btn-primary' %>
            <%end%>
          
           
        </div>
        <br>
<button id="player-two-button" class="btn btn-primary"><a  href= "<%= transactionhistories_url %>"  data-remote="true"><%= @battles2["name"] %></a></button>

    </div>
</div>



<script>


document.getElementById('next-fight').style.visibility="hidden";
document.getElementById('fight-button').style.visibility="hidden";
document.getElementById('bet-interface').style.visibility="hidden";
document.getElementById('bet-interface-for-player-two').style.visibility="hidden";


document.getElementById('player-one-button').addEventListener('click',function(){
document.getElementById('bet-interface').style.visibility="visible";
document.getElementById('bet-interface-for-player-two').style.visibility="hidden";
document.getElementById('qwerty').innerHTML=""
})

document.getElementById('player-two-button').addEventListener('click',function(){
document.getElementById('bet-interface-for-player-two').style.visibility="visible";
document.getElementById('bet-interface').style.visibity="hidden";
document.getElementById('qwerty').innerHTML=""
 
})

document.getElementById('submit-button-one').addEventListener('click',function(){
  document.getElementById('bet-interface').style.visibility="hidden";
document.getElementById('bet-interface-for-player-two').style.visibility="hidden";
})

document.getElementById('submit-button-two').addEventListener('click',function(){
  document.getElementById('bet-interface').style.visibility="hidden";
document.getElementById('bet-interface-for-player-two').style.visibility="hidden";
})

let error = function(){
  document.getElementById('qwerty').innerHTML = "Insufficent funds"
}
let playerOneBet = function(){
  document.getElementById('amount-bet-for-player-one').innerHTML = "<%= @transactionhistory.amountofbet %>"
}
let playerTwoBet = function(){
  document.getElementById('amount-bet-for-player-two').innerHTML = "<%= @transactionhistory.amountofbet %>"
}
document.getElementById("next-fight").addEventListener("click",function(){
  location.reload();
})



</script>
 </body>

app/views/transactionhistories/new.html.erb
<h1>New Transactionhistory</h1>

<%= render 'form', transactionhistory: @transactionhistory %>

<%= link_to 'Back', transactionhistories_path %>

app/views/transactionhistories/new.js.erb
document.getElementById("testing").value= <%= @transactionhistory.amountofbet %>

app/views/transactionhistories/topup.html.erb
<%= @userpoints %>

<%= link_to "back" , transactionhistories_path %>